server:
  port: 8887

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/CREWUP-MSA/config.git
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}